name: netzap-server
services:
  mongo:
    container_name: database
    image: bitnami/mongodb:7.0.12
    user: root
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=prisma
      - MONGODB_ROOT_PASSWORD=prisma
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - 27017:27017
    volumes:
      - ./.docker/mongo:/bitnami/mongodb
